export const vehicles = [
    {
      vehicleNumber: "KA01AB1234",
      status: "Moving",
      runningTime: "1hr 33mins",
      destination: "Ramappa Layout, 1st Stage, BTM Layout",
      distanceTravelled: "90km",
      speed: "40km/hr",
    },
    {
      vehicleNumber: "KA02CD5678",
      status: "Parked",
      runningTime: "0hr 0mins",
      destination: "Electronic City, Phase 1",
      distanceTravelled: "0km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA03EF9012",
      status: "Offline",
      runningTime: "N/A",
      destination: "Unknown",
      distanceTravelled: "N/A",
      speed: "N/A",
    },
    {
      vehicleNumber: "KA04GH3456",
      status: "Idle",
      runningTime: "2hr 15mins",
      destination: "Indiranagar, 12th Main",
      distanceTravelled: "10km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA05IJ7890",
      status: "Moving",
      runningTime: "3hr 50mins",
      destination: "Whitefield, ITPL Main Road",
      distanceTravelled: "120km",
      speed: "60km/hr",
    },
    {
      vehicleNumber: "KA06KL1234",
      status: "Parked",
      runningTime: "0hr 0mins",
      destination: "Kormangala, Block 3",
      distanceTravelled: "0km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA07MN5678",
      status: "Offline",
      runningTime: "N/A",
      destination: "Unknown",
      distanceTravelled: "N/A",
      speed: "N/A",
    },
    {
      vehicleNumber: "KA08OP9012",
      status: "Idle",
      runningTime: "1hr 45mins",
      destination: "Bannerghatta Road, Arekere",
      distanceTravelled: "5km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA09QR3456",
      status: "Moving",
      runningTime: "2hr 10mins",
      destination: "JP Nagar, 6th Phase",
      distanceTravelled: "70km",
      speed: "50km/hr",
    },
    {
      vehicleNumber: "KA10ST7890",
      status: "Parked",
      runningTime: "0hr 0mins",
      destination: "Basavanagudi, Bull Temple Road",
      distanceTravelled: "0km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA11UV1234",
      status: "Moving",
      runningTime: "3hr 30mins",
      destination: "Yelahanka, New Town",
      distanceTravelled: "100km",
      speed: "55km/hr",
    },
    {
      vehicleNumber: "KA12WX5678",
      status: "Idle",
      runningTime: "1hr 20mins",
      destination: "Malleshwaram, 18th Cross",
      distanceTravelled: "15km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA13YZ9012",
      status: "Parked",
      runningTime: "0hr 0mins",
      destination: "Hebbal, Ring Road",
      distanceTravelled: "0km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA14AB3456",
      status: "Moving",
      runningTime: "4hr 10mins",
      destination: "KR Puram, Old Madras Road",
      distanceTravelled: "130km",
      speed: "60km/hr",
    },
    {
      vehicleNumber: "KA15CD7890",
      status: "Offline",
      runningTime: "N/A",
      destination: "Unknown",
      distanceTravelled: "N/A",
      speed: "N/A",
    },
    {
      vehicleNumber: "KA16EF1234",
      status: "Idle",
      runningTime: "2hr 5mins",
      destination: "Jayanagar, 4th Block",
      distanceTravelled: "20km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA17GH5678",
      status: "Moving",
      runningTime: "1hr 50mins",
      destination: "Hosur Road, Singasandra",
      distanceTravelled: "80km",
      speed: "70km/hr",
    },
    {
      vehicleNumber: "KA18IJ9012",
      status: "Parked",
      runningTime: "0hr 0mins",
      destination: "BTM Layout, 2nd Stage",
      distanceTravelled: "0km",
      speed: "0km/hr",
    },
    {
      vehicleNumber: "KA19KL3456",
      status: "Offline",
      runningTime: "N/A",
      destination: "Unknown",
      distanceTravelled: "N/A",
      speed: "N/A",
    },
    {
      vehicleNumber: "KA20MN7890",
      status: "Moving",
      runningTime: "2hr 45mins",
      destination: "Majestic, Gandhinagar",
      distanceTravelled: "95km",
      speed: "45km/hr",
    },
  ];